version: "3"

services:
    # Server running on the public network
    server:
        image: totem-stun
        cap_add:
            # Need NET_ADMIN capacity to allocate IP address
            - NET_ADMIN
        networks:
            public_net:
                ipv4_address: 172.19.0.2
        entrypoint: >
            /bin/sh -c "echo 'Allocating IP address 172.19.0.4' && \
            PUBLIC_IF=$$(ip -o -4 addr list | grep 172.19.0.2 | awk '{print $$2}') && \
            ip addr add 172.19.0.4/24 dev $$PUBLIC_IF && \
            echo 'Starting stun server...' && \
            ./target/release/server"
    # NAT server that bridges private and public networks
    nat:
        image: alpine:latest
        # Need privilege to call sysctl
        privileged: true
        cap_add:
            - NET_ADMIN
        networks:
            private_net:
                ipv4_address: 172.18.0.2
            public_net:
                ipv4_address: 172.19.0.3
        command: sh -c "
            apk add --no-cache iptables iproute2 && \
            sysctl -w net.ipv4.ip_forward=1 && \
            PUBLIC_IF=\$(ip -o -4 addr list | grep 172.19.0.3 | awk '{print \$2}') && \
            iptables -t nat -A POSTROUTING -o $${PUBLIC_IF} -j MASQUERADE && \
            tail -f /dev/null
            "
    # Client running on private network
    client:
        image: totem-stun
        cap_add:
            - NET_ADMIN
        depends_on:
            - nat
        networks:
            private_net:
        # Connect to NAT server
        command: sh -c "
            apk add --no-cache curl && \
            ip route del default && \
            ip route add default via 172.18.0.2 && \
            ./target/release/client && \
            tail -f /dev/null
            "
networks:
    private_net:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24
    public_net:
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/24